com:
  name: 菜鸟程序猿
  title: 学习springboot
  desc: ${com.name}正在努力${com.title}
  value: ${random.value}
  number: ${random.int}
  bignumber: ${random.long}
  test1: ${random.int(10)}
  test2: ${random.int(10,20)}
spring:
  profiles:
    #这里配置不同环境读取的配置环境，dev（开发环境），test（测试环境），prod（生产环境）spring回去读取相应的配置文件
     active: dev
